# Generated by Django 4.1.2 on 2023-04-04 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_profile_image'),
        ('products', '0005_product_product_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.profile'),
        ),
    ]
