# Generated by Django 4.1.2 on 2023-04-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_college',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
